### ISSUE TITLE
[Salvo] Reformat imports in run_benchmark.py

### ISSUE THREAD

**Issue by landesherr** [envoyproxy/envoy-perf#114]
The issue came up in PR #113 that Salvo's use of import renaming with respect to benchmarks is not in line with the style guide.
Need to reformat the imports for `fully_dockerized_benchmark` and `scavenging_benchmark` in `run_benchmark.py` per [imports guidance](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#224-decision)

**Comment by abaptiste** [comment]
@mum4k This appears to be addressed.  Could you close this issue?  Thanks!

**Comment by mum4k** [comment]
Thank you for pointing this out.
