### ISSUE TITLE
Can you please give a more detailed readme of how to use salvo?

### ISSUE THREAD

**Issue by jiangdongzi** [envoyproxy/envoy-perf#122]
I do not know how what files should put in the `testDir`  of `Fully Dockerized Benchmark`. Hope you can give an example.

**Comment by mum4k** [comment]
Hi @jiangdongzi, you raise a good point about the lack of detailed documentation. The development of the Salvo project has been paused temporarily. We expect to get to it in the future, at which point we will also provide better documentation on how to use it.

I am happy to provide answers meanwhile. The `testDir` is optional and can contain tests defined by the user. Salvo runs the [Nighthawk benchmarks](https://github.com/envoyproxy/nighthawk/tree/main/benchmarks) implementation. So if the user wanted to provide their own test cases, they would put test files like [this one](https://github.com/envoyproxy/nighthawk/blob/main/benchmarks/test/test_discovery.py) into the `testDir`.

Hope this helps.

**Comment by gyohuangxin** [comment]
Hi @mum4k , I'm looking at this project these days and I think it'll be very helpful for me and envoy project. Do you have any updates about Salvo itself and any plan to integrate it into Envoy CI system? Thanks.

**Comment by mum4k** [comment]
Thank you for reaching out @gyohuangxin, we have a fairly concrete plan at this point. We are aiming to implement a solution meeting [these requirements](https://docs.google.com/document/d/1mAma-ksRN0OIBInoZKUdjdaIhK2nTQxFnCujq2fKi4E/edit) which includes integration into Envoy's CI. We expect to have a person full time on this within the next 6 months.

Happy to discuss any of the details and/or accept any help you may be willing to offer.

**Comment by gyohuangxin** [comment]
@mum4k Thank you for the answer.

**Comment by gyohuangxin** [comment]
@mum4k I'm going to draft a document about the local execution mode of Salvo, can you assign this issue to me? Thanks.

**Comment by mum4k** [comment]
Thank you for your help @gyohuangxin.

**Comment by gyohuangxin** [comment]
@mum4k I raise a PR to revise the doc of the local execution mode of Salvo, it's not perfect, any comments from you would of great help. Thanks!

**Comment by gyohuangxin** [comment]
cc @jiangdongzi I'll also appreciate it if you have any comments.

**Comment by gyohuangxin** [comment]
@mum4k I raised a PR to add another detailed documentation 'Measure Envoy's Performance Change with an A/B Testing', can you review and leave some comments?

**Comment by mum4k** [comment]
Thank you @gyohuangxin I will take a look. As a heads up, this will take a few days, as I am planning to execute a workflow according to the instructions, so that I can provide useful feedback.

**Comment by gyohuangxin** [comment]
@mum4k Sure, it's necessary. Thanks.
