### ISSUE TITLE
[Salvo] Use Salvo to measure real commits in Envoy repo

### ISSUE THREAD

**Issue by gyohuangxin** [envoyproxy/envoy-perf#131]
Use Salvo to measure real commits in Envoy repo to find out what can be improve for Salvo and its test cases.
Then convert the example of [fake commits](https://github.com/envoyproxy/envoy-perf/blob/main/salvo/ENVOY_DEVELOP_WORKFLOW.md) to the real commits.

**Comment by gyohuangxin** [comment]
@mum4k  Sorry for the absence due to some critical work, I tried to measure real commits you mentioned before, but the commit id seems not be found from main branch in cloned repo. 
```
$ git clone https://github.com/gyohuangxin/envoy && cd envoy
$ git checkout 461bec3bf2a29b56d1117f28df3a0894914d3952
fatal: reference is not a tree: 461bec3bf2a29b56d1117f28df3a0894914d3952
```
This commit id was 461bec3bf2a29b56d1117f28df3a0894914d3952
![image](https://user-images.githubusercontent.com/42127654/161886376-d0a6136d-ce1f-4e49-a6e8-6fff0f042ec2.png)

Do you have any idea about how to fix it?

**Comment by mum4k** [comment]
I think `461bec3bf2a29b56d1117f28df3a0894914d3952` is a commit ID before https://github.com/envoyproxy/envoy/pull/19115 was merged onto the main branch.

Envoy uses Squash commits, which means all commits reviewed in the PR get squashed together and result in a single commit into the main branch. We should be using [this commit ID](https://github.com/envoyproxy/envoy/commit/02dff6e0235e2f497fb57eb0b7c07cc091c538df) instead. This can be found in the conversation history of https://github.com/envoyproxy/envoy/pull/19115 where it was merged in:

<img width="942" alt="Screen Shot 2022-04-06 at 11 26 25 PM" src="https://user-images.githubusercontent.com/5315344/162114311-a2fb63ea-ce81-4fbe-b2b0-ff8ff2e872cc.png">

Verified that this is available in a clone of the Envoy repository:

```
$ git clone https://github.com/envoyproxy/envoy && cd envoy
$ git log | grep 02dff6e0235e2f497fb57eb0b7c07cc091c538df
commit 02dff6e0235e2f497fb57eb0b7c07cc091c538df
```

**Comment by gyohuangxin** [comment]
@mum4k Thank you, it confused me for a long time. Now it works.
