### ISSUE TITLE
Benchmark tool doesn't produce any output

### ISSUE THREAD

**Issue by jimmy-huang** [envoyproxy/envoy-perf#21]
I tried to run the benchmark, it just shows instance created, but it is stuck there forever, and nothing is printed in the console, and no benchmark.log is generated

python2 benchmark.py --local_envoy_binary_path  ../envoy/bazel-bin/source/exe/envoy-static --scripts_path . --envoy_config_path ../envoy/examples/lua/  --username $user --envoy_hash None --project envoy-perf --service_account envoy-service@envoy-perf.iam.gserviceaccount.com --cpu 8 --ram 48
Instance created successfully.
Instance is running successfully.

I sshed into the VM that was created and there's nothing in there, so I am not sure if I am pass the configurations and the scripts path correctly to run the benchmark tool.

**Comment by htuch** [comment]
@jimmy-huang I think this repository is largely stale, it reflects work done by @sohamm17 last year, but we haven't had any bandwidth in OSS Envoy to productionize this in CI. If you want to fix, PRs welcome. Ideally we get folks able to take on the task of making this a continuous perf measurement system in the future.

**Comment by jimmy-huang** [comment]
@htuch thanks for the quick reply, yeah, it would be nice if someone can help fix this issue, we are not even sure what kind of performance this tool measures, since we just came across this and want to spin it up to see what it does, but looks like we are on our own for now.
