### ISSUE TITLE
Distributed Load Testing of Envoy Data Planes

### ISSUE THREAD

**Issue by leecalcote** [envoyproxy/envoy-perf#72]
Many performance benchmarks are limited to single instance load generation (single pod load generator). This limits the amount of traffic that can be generated to output of the single machine that the benchmark tool runs on in or out of a cluster. Overcoming this limitation would allow for more flexible and robust testing. Distributed load testing in parallel poses a challenge when merging results without losing the precision we need to gain insight into the high tail percentiles.

I'm opening this issue as a potential Google Summer of Code project. The [Meshery](https://meshery.io) project is considering enhancing its existing load generation and analysis to include distributed perf testing of Envoy and Envoy-based data planes.

**Comment by swhsiang** [comment]
> The Meshery project is considering enhancing its existing load generation and analysis to include distributed perf testing of Envoy and Envoy-based data planes.

I notice Meshery project has its own load generation command. (ex: `mesheryctl perf --name "a quick stress test" --url http://192.168.1.15/productpage --qps 300 --parallel-requests 2 --duration 30s --load-generator wrk2`)

Are you suggesting working on Meshery project to improve its load generation for Envoy?

I am looking for a project to work on for Google Summer of Code event and hopefully submit the proposal before its deadline (today 2pm EST). I will appreciate if you can clarify some questions I have.

**Comment by jmarantz** [comment]
quick comment: Envoy has its own load-generator project, https://github.com/envoyproxy/nighthawk , which can run as a gRPC-controlled server, and thus scaled up in the fashion described here.

It would definitely be interesting to discuss the possibilities of an OSS distributed load-test framework.

@htuch @oschaaf

**Comment by swhsiang** [comment]
@jmarantz Thanks for your quick reply. Looks like nighthawk is a single instance load-generator. I also notice users can specify the format of the output of nighthawk (ex: json|human, yaml, dotted ,fortio).

According to what @leecalcote said,
> The Meshery project is considering enhancing its existing load generation and analysis to include distributed perf testing of Envoy and Envoy-based data planes.

Here is an idea:
Building a distributed load-test framework on top of nighthawk project and exports the data in portable format which might be supported by Meshery project.

Is this something all of you are looking for?

BTW, please correct if my understanding is wrong. The envoy-perf project is a collection of python scripts that simulates some important scenarios of envoy and generates some metrics for further analysis. The envoy-perf project is built on top of nighthawk.

**Comment by jmarantz** [comment]
envoy-perf is a collection of mostly obsolete scripts, not built on NH :)

**Comment by kushthedude** [comment]
Currently, Meshery Project only supports load generation using fortio & wrk2 out of which neither is a parallel load generator, hence we need a distributed load testing framework to improve the performance benchmarking and load testing of various service mesh interfaces using Meshery. Meshery is also considering to use Vegeta for distributed load testing. There are some issues with the following in terms of report storage which needs further clarification from the community. Hence this is a potential GSoC Project which aims to improve the Envoy-Perf which I saw after seeing the code is not much maintained. We can further look into building a load-generation for service meshes over Nighthawk which can benefit both the communities. But if Vegeta can be somehow optimised to run over Meshery, it would decrease the workload and writing of the distributed load tester from scratch.

**Comment by htuch** [comment]
I think using multiple Nighthawks in a distributed load generator would be a forward looking move, since Nighthawk is intended to be a superset of Fortio/WRK2 functionality. CC @envoyproxy/nighthawk-maintainers

**Comment by shivaylamba** [comment]
I definitely agree, we need support for multiple load generators to be used as it gives us the flexibility. Support for parallel load generators is what is needed for now. Nighthawk might be worth looking at.

**Comment by leecalcote** [comment]
All, this is encouraging in that the combination of Meshery to schedule and coordinate various performance test configurations for not only one type of service mesh, but to analyze system and service behavior across a heterogenous set of service meshes and their workloads (federated or unfederated) is of broader interest and valuable considering the number of service meshes using Envoy as their data plane.

Supporting multiple types of load generators is an intentional point of [extensibility in Meshery](https://meshery.layer5.io/docs/extensibility). Nighthawks' ability to output performance statistics in a fortio-compatible format is quite attractive.

**Comment by mum4k** [comment]
Speaking on behalf of @envoyproxy/nighthawk-maintainers, we too are also looking at ways how to enable Nighthawk to scale horizontally (distributed load generation) and are hoping to spin up some work in this area in the coming months. We will be more than happy to cooperate and pool ideas.

**Comment by kushthedude** [comment]
Sounds great @mum4k!

**Comment by leecalcote** [comment]
A design spec is up for review - https://docs.google.com/document/d/1_hhQ5w1iLClgf7RvboI6il-eMKKAVPwz50GHm2VN4Bg/edit?usp=sharing. Please engage and comment at-will.
