### ISSUE TITLE
Implement coverage check in CI

### ISSUE THREAD

**Issue by mum4k** [envoyproxy/envoy-perf#94]
We should implement a CI check that will generate HTML coverage report to help with PR reviews and verify both total and incremental coverage against set thresholds. This will ensure that:

- newly added code has sufficient coverage
- total coverage in the salvo codebase doesn't regress below our goal

**Comment by gyohuangxin** [comment]
I think Codecov will be the tool to implement it, and here is the example we can refer to: https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/
